function today(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
const icons={oggi:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',agenda:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18"/>',allievi:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0112 0v3m1-16a3 3 0 010 6m2 4a5 5 0 013 5"/>',allenamenti:'<path d="M5 4h14v17H5zM9 2v4m6-4v4M8 10h8m-8 4h8m-8 4h5"/>',progressi:'<path d="M3 3v18h18M6 16l5-5 4 3 6-8"/>'};
icons.corsi='<path d="M3 7V4h7l2 3h9v14H3z"/>';
const names={corsi:'Corsi',oggi:'Oggi',agenda:'Agenda',allievi:'Allievi',allenamenti:'Allievi',progressi:'Il mio percorso'};
const people=[];
let lessons=[];
let route='oggi',selectedDate=today(),club='Tutti i circoli',query='';const skillNames=['Diritto e rovescio','Volée','Gioco sui vetri','Scelte tattiche','Movimento in campo'];const $=s=>document.querySelector(s);const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const svg=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${icons[k]||icons.oggi}</svg>`;const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'});const who=l=>l.players.map(id=>people.find(p=>p.id===id)?.name||'Allievo').join(' · ');function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').style.display='none',3500)}
function title(eye,name,desc,button=''){return `<div class="page-title"><div><div class="eyebrow">${eye}</div><h1>${esc(name)}</h1><p>${esc(desc)}</p></div>${button}</div>`}function lessonRow(l){return `<div class="lesson"><div class="time">${l.time}<small>${l.duration} min</small></div><div class="lesson-info ${l.club==='Sporting Club'?'blue':''}"><strong>${esc(who(l))}</strong><p>${esc(l.focus||l.title)}</p><small>${esc(l.club)}</small>${l.players.length>1?`<span class="tag blue">${l.players.length} allievi · ${l.players.filter(pid=>participantPresent(l,pid)).length} presenti</span>`:l.present?'<span class="tag">Presenza registrata</span>':''}</div><button class="arrow" aria-label="Apri lezione delle ${l.time}" data-action="lesson" data-id="${l.id}">↗</button>${l.players.some(pid=>contextAccess(pid,l.course_id,true))&&l.players.length>1?`<div class="lesson-actions"><button class="btn light" data-action="lesson" data-id="${l.id}">Presenze e schede</button></div>`:contextAccess(l.players[0],l.course_id,true)?`<div class="lesson-actions"><button class="btn light" data-action="presence" data-id="${l.id}">${l.present?'Annulla presenza':'Segna presenza'}</button><button class="btn light" data-action="lesson-journal" data-id="${l.players[0]}" data-lesson="${l.id}">Annota</button></div>`:''}</div>`}

function agenda(){
  const list=lessons.filter(l=>!l.cancelled&&l.date===selectedDate&&(club==='Tutti i circoli'||l.club===club));
  return title('Appuntamenti','Agenda','Le tue lezioni, giorno per giorno.','<button class="btn" data-action="new-lesson">＋ Nuova lezione</button>')+`<div class="toolbar"><label>Circolo<select id="club">${['Tutti i circoli',...new Set(lessons.map(l=>l.club))].map(c=>`<option ${c===club?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Data<input id="agenda-date" type="date" value="${selectedDate}"></label></div><div class="week">${Array.from({length:7},(_,i)=>{const base=new Date(selectedDate+'T12:00:00');base.setDate(base.getDate()-((base.getDay()+6)%7)+i);const d=[base.getFullYear(),String(base.getMonth()+1).padStart(2,'0'),String(base.getDate()).padStart(2,'0')].join('-');const count=lessons.filter(l=>!l.cancelled&&l.date===d&&(club==='Tutti i circoli'||l.club===club)).length;return `<button class="day ${selectedDate===d?'selected':''}" aria-pressed="${selectedDate===d}" aria-label="${dateLabel(d)}, ${count} lezioni" data-action="date" data-date="${d}">${['LUN','MAR','MER','GIO','VEN','SAB','DOM'][i]}<strong>${base.getDate()}</strong><small>${count?count+' lez.':'—'}</small></button>`}).join('')}</div><section class="panel"><div class="panel-head"><h2>${dateLabel(selectedDate)}</h2><span class="tag">${list.length} lezioni</span></div>${list.sort((a,b)=>a.time.localeCompare(b.time)).map(lessonRow).join('')||'<div class="empty"><h3>Nessuna lezione in programma.</h3><p>Seleziona un altro giorno per consultare l’agenda.</p></div>'}</section>`;
}

function modal(title,body){$('#modal').innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="close" aria-label="Chiudi" data-action="close">×</button></div>${body}`;if(!$('#modal').open)$('#modal').showModal()}function close(){$('#modal').close()}
function participantPresent(l,pid){return l.participants?.find(p=>p.student===pid)?.present??(l.players.length===1&&l.present)}
function missingJournals(l){return l.players.filter(pid=>!journals.some(j=>j.lessonId===l.id&&j.student===pid))}
function openLesson(id){
 const l=lessons.find(x=>x.id===id);if(!l)return;
 modal(esc(l.focus),`<span class="tag">${dateLabel(l.date)} · ${l.time}</span><p>${esc(l.club)} · ${l.duration} minuti</p><div class="notice">${esc(l.focus)}</div><div class="actions"><button class="btn light" data-action="lesson-edit" data-id="${id}">Modifica lezione</button><button class="btn light" data-action="file-share" data-kind="lesson" data-id="${id}">Esporta lezione</button><button class="btn light danger" data-action="lesson-delete" data-id="${id}">Elimina lezione</button></div><div class="participants-list">${l.players.map(pid=>`<section class="participant-row"><div><h3>${esc(people.find(p=>p.id===pid)?.name||'Allievo')}</h3><small>${participantPresent(l,pid)?'Presenza registrata':'Presenza non registrata'}</small></div>${contextAccess(pid,l.course_id,true)?`<div class="actions"><button class="btn light" data-action="presence" data-id="${id}" data-student="${pid}">${participantPresent(l,pid)?'Annulla presenza':'Segna presenza'}</button><button class="btn" data-action="lesson-journal" data-id="${pid}" data-lesson="${id}">${journals.some(j=>j.lessonId===id&&j.student===pid)?'Apri allenamento':'Annota allenamento'}</button></div>`:''}</section>`).join('')}</div>${owns(l)?`<label class="field" style="margin-top:16px">Nota privata della lezione<textarea id="lesson-note" placeholder="Appunti sul lavoro svolto con il gruppo…">${esc(l.note||'')}</textarea></label><div class="form-actions"><button class="btn light" data-action="save-note" data-id="${id}">Salva nota</button></div>`:'<p class="form-help">Le osservazioni personali sono nel tuo diario degli allenamenti.</p>'}`);
}
function newLesson(id=null){
 const previous=id?lessons.find(l=>l.id===id):null;if(id&&!previous)return;
 const cid=previous?.course_id??activeCourse,candidates=people.filter(p=>!cid||courseStudents.some(m=>m.course_id===cid&&m.student===p.id));
 if(!candidates.length){toast('Aggiungi prima un allievo in questo spazio.');return}
 const selected=previous?.players||[],durations=[...new Set([60,90,30,120,...(previous?[previous.duration]:[])])];
 modal(previous?'Modifica lezione':'Organizza una lezione',`<form id="lesson-form" data-id="${previous?.id||''}" data-course="${cid||''}"><div class="form-grid"><label class="field">Data<input name="date" type="date" value="${previous?.date||selectedDate}" required></label><label class="field">Orario<input name="time" type="time" value="${previous?.time||'17:00'}" required></label><label class="field">Circolo<input name="club" required maxlength="100" value="${esc(previous?.club||'')}" placeholder="Nome del circolo"></label><label class="field">Durata<select name="duration">${durations.map(n=>`<option value="${n}" ${n===(previous?.duration||60)?'selected':''}>${n} minuti</option>`).join('')}</select></label><fieldset class="participant-picker full"><legend>Allievi · da 1 a 4</legend><p class="form-help">Scegli un allievo per una lezione individuale o 2–4 per un gruppo.</p>${candidates.map(p=>`<label><input type="checkbox" name="students" value="${p.id}" ${selected.includes(p.id)?'checked':selected.length>=4?'disabled':''}><span>${esc(p.name)}<small>${esc(p.level)}</small></span></label>`).join('')}<p id="participant-count" role="status">${selected.length} di 4 selezionati</p></fieldset><label class="field full">Obiettivo della lezione<input name="focus" maxlength="160" value="${esc(previous?.focus||'')}" placeholder="Es. volée e controllo della rete" required></label></div>${previous?'<p class="form-help">Le presenze e la nota privata restano conservate. Data, orario e circolo vengono aggiornati anche negli allenamenti collegati. Se rimuovi un partecipante, le sue schede restano nel diario come allenamenti indipendenti.</p>':''}<p id="form-error" role="alert" class="save-error"></p><div class="form-actions"><button type="button" class="btn light" data-action="close">Annulla</button><button class="btn" type="submit">${previous?'Salva modifiche':'Crea lezione'}</button></div></form>`);
}
function hasConflict(date,time,duration,exclude){let start=Number(time.slice(0,2))*60+Number(time.slice(3));return lessons.some(l=>{let t=Number(l.time.slice(0,2))*60+Number(l.time.slice(3));return !l.cancelled&&l.id!==exclude&&l.date===date&&start<t+l.duration&&start+duration>t})}
