names.backup='Backup';names.condivisione='Condividi';
icons.backup='<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>';
icons.condivisione='<circle cx="5" cy="12" r="3"/><circle cx="19" cy="5" r="3"/><circle cx="19" cy="19" r="3"/><path d="m8 10 8-4M8 14l8 4"/>';
function backupPage(){return title('I tuoi dati','Backup e ripristino','Il diario è salvato in questo browser, su questo dispositivo.')+`<div class="file-panels"><section class="panel"><h2>Conserva una copia del diario</h2><p>Il backup completo include allievi, corsi, lezioni, presenze, allenamenti, valutazioni e note private. Usalo per recuperare il diario o trasferirlo su un altro dispositivo.</p><p>Conserva questo file per te: per inviare lezioni a un collega usa “Condividi”, che esclude le note private.</p><button class="btn" data-action="backup-download">Scarica backup completo</button></section><section class="panel"><h2>Ripristina un backup</h2><p>Puoi aprire un backup di questa versione o della precedente app online. Il ripristino sostituisce il diario su questo dispositivo: vedrai un riepilogo prima di confermare.</p><label class="field">File di backup (.json)<input id="backup-file" type="file" accept=".json,application/json"></label><p id="backup-status" role="status"></p></section><section class="panel"><h2>Uso offline sul telefono</h2><p>Apri l’app con Internet e attendi la conferma “Pronta offline”. Poi aggiungila alla schermata Home: su iPhone usa Safari e “Aggiungi alla schermata Home”; su Android usa l’opzione di installazione del browser.</p><p>Apri l’icona una prima volta con Internet e verifica la conferma. Puoi quindi lavorare senza connessione. Ogni dispositivo mantiene un diario separato.</p><p>Scarica regolarmente un backup, soprattutto prima di cambiare telefono, browser o indirizzo dell’app, oppure di cancellare i dati del browser.</p><button class="btn light" data-action="install-help">Come installarla</button><p id="storage-status" role="status"></p><button class="btn light" data-action="persistent-storage">Proteggi l’archiviazione locale</button></section></div>`}
function sharingPage(){return title('Tra maestri','Condividi tramite file','Invia una copia delle lezioni e importala in un altro diario.')+`<div class="file-panels"><section class="panel"><h2>Esporta una parte del diario</h2><p>Scegli “Esporta lezione” nei dettagli dell’agenda, “Esporta allenamento” in una scheda, “Esporta corso” nella cartella o “Esporta diario” nella scheda di un allievo.</p><p>Il file include gli esercizi, i commenti e i voti relativi alla scelta. Le note private sono sempre escluse. Il diario di un singolo allievo esclude nomi e schede degli altri partecipanti alle lezioni di gruppo; il corso include soltanto i dati del corso.</p><p>Scarica il file .json e mandalo al collega con il mezzo che preferisci. Il collega lo apre qui, nella propria app.</p><div class="actions"><a class="btn light" href="#agenda">Scegli una lezione</a><a class="btn light" href="#corsi">Scegli un corso</a><a class="btn light" href="#allievi">Scegli un diario</a></div></section><section class="panel"><h2>Importa il file di un collega</h2><p>Verranno aggiunte copie modificabili, senza sovrascrivere il tuo diario. Reimportare gli stessi dati non crea duplicati e conserva le modifiche locali. I dati già importati non vengono aggiornati automaticamente.</p><label class="field">File condiviso (.json)<input id="share-file" type="file" accept=".json,application/json"></label><p id="share-status" role="status"></p></section></div>`}
function portableBackup(){return {format:'campo-backup',version:2,createdAt:new Date().toISOString(),origin:localState.origin,data:snapshot()}}
function downloadJSON(payload,filename){const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function downloadBackup(){downloadJSON(portableBackup(),'campo-backup-'+today()+'.json')}
function counts(data){return `${data.students.length} allievi, ${data.courses.length} corsi, ${data.lessons.length} lezioni, ${data.training_sessions.length} allenamenti, ${data.general_ratings.length} valutazioni`}
function exportShare(kind,id){
 const payload=CampoFiles.bundle(snapshot(),localState.origin,kind,id),labels={lesson:'lezione',journal:'allenamento',student:'diario',course:'corso'},filename='campo-'+labels[kind]+'-'+today()+'.json';
 const file=new File([JSON.stringify(payload,null,2)],filename,{type:'application/json'}),native=!!navigator.canShare?.({files:[file]});
 modal('Esporta '+labels[kind],`<p>Il file contiene: <strong>${esc(counts(payload.data))}</strong>.</p><p>Le note private sono escluse. Invia il file al collega: potrà aprirlo in “Condividi → Importa il file di un collega”. Questa è una copia indipendente, senza sincronizzazione.</p><div class="form-actions"><button class="btn" id="share-download">Scarica file .json</button>${native?'<button class="btn light" id="share-native">Invia file…</button>':''}</div><p id="export-status" role="status"></p>`);
 $('#share-download').onclick=()=>{downloadJSON(payload,filename);$('#export-status').textContent='File pronto. Puoi inviarlo dal telefono o dal computer.'};
 if(native)$('#share-native').onclick=async()=>{try{await navigator.share({files:[file],title:'Diario del Coach'});$('#export-status').textContent='File condiviso.'}catch(e){if(e.name!=='AbortError')$('#export-status').textContent='Scarica il file e invialo dal dispositivo.'}};
}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el||!localReady||busy)return;try{if(el.dataset.action==='backup-download'){downloadBackup();toast('Backup pronto per il download.')}else if(el.dataset.action==='file-share')exportShare(el.dataset.kind,Number(el.dataset.id));else if(el.dataset.action==='persistent-storage'){const granted=await navigator.storage?.persist?.();$('#storage-status').textContent=granted?'Archiviazione persistente attivata. Conserva comunque un backup.':'Il browser gestisce lo spazio automaticamente. Conserva regolarmente un backup.'}}catch(error){toast(saveFailure(error))}});
document.addEventListener('change',async e=>{
 if(!['backup-file','share-file'].includes(e.target.id)||!localReady||busy)return;const input=e.target,file=input.files[0];if(!file)return;const restore=input.id==='backup-file',status=$(restore?'#backup-status':'#share-status');let b;busy=true;
 try{if(file.size>50*1024*1024)throw Error('File troppo grande: il limite è 50 MB.');b=CampoFiles.parse(JSON.parse(await file.text()));if(b.format!==(restore?'campo-backup':'campo-share'))throw Error(restore?'Questo è un file condiviso: aprilo in Condividi.':'Questo è un backup completo: aprilo in Backup.')}catch(error){status.textContent=error instanceof SyntaxError?'File JSON non leggibile. Nessun dato è stato modificato.':saveFailure(error);return}finally{busy=false;input.value=''}
 let preview;try{if(!restore)preview=CampoFiles.merge(snapshot(),b,nextId,localState.origin)}catch(error){status.textContent=saveFailure(error);return}
 const collisions=!restore?preview.data.lessons.filter(l=>!lessons.some(x=>x.id===l.id)&&hasConflict(l.date,l.time,l.duration,null)).length:0;
 modal(restore?'Conferma ripristino':'Conferma importazione',`<p>File del ${esc(new Date(b.createdAt).toLocaleString('it-IT'))}: <strong>${esc(counts(b.data))}</strong>.</p>${restore?'<p>Questo sostituirà tutti i dati del diario su questo dispositivo, incluse le note private. Scarica un backup dei dati attuali prima di continuare.</p><button class="btn light" data-action="backup-download">Scarica prima il diario attuale</button>':`<p>${preview.added} nuove voci · ${preview.skipped} voci già presenti, che saranno conservate.</p><p>Le copie importate saranno modificabili e indipendenti dal diario del collega.</p>${collisions?`<p class="notice">${collisions} lezioni coincidono con orari già occupati. Saranno conservate come parte del diario ricevuto.</p>`:''}`}<form id="file-confirm"><label class="share-choice"><input type="checkbox" required> ${restore?'Confermo la sostituzione del diario':'Confermo l’aggiunta delle copie al diario'}</label><div class="form-actions"><button type="button" class="btn light" data-action="close">Annulla</button><button class="btn">${restore?'Ripristina diario':'Importa copie'}</button></div></form>`);
 $('#file-confirm').addEventListener('submit',async ev=>{ev.preventDefault();if(busy||!localReady)return;await mutate(()=>{if(restore){const data=structuredClone(b.data);for(const t of CampoFiles.tables.filter(t=>t!=='course_students'))for(const r of data[t])r.source=r.source||{origin:b.origin,table:t,id:r.id};hydrate(data)}else hydrate(CampoFiles.merge(snapshot(),b,nextId,localState.origin).data)},()=>{close();navigate(restore?'backup':'condivisione');toast(restore?'Diario ripristinato sul dispositivo.':'Copie importate nel diario.')})});
});
