/* Tactical board: temporary in-memory state, reset on page reload. */
names.lavagna='Lavagna';icons.lavagna='<rect x="4" y="3" width="16" height="18" rx="1"/><path d="M4 12h16M4 7h16M4 17h16M12 7v10"/>';
const boardInitial=()=>({players:[{x:150,y:210},{x:350,y:210},{x:150,y:790},{x:350,y:790},{x:250,y:620}],lines:[]});
let boardState=boardInitial(),boardUndo=[],boardTool='move',boardColor='#e5f52a';
function resetBoard(){boardState=boardInitial();boardUndo=[];boardTool='move'}
function boardPage(){return title('Durante la lezione','Lavagna','Sposta i giocatori e la pallina, poi disegna il prossimo scambio.')+`<section class="panel tactical-board"><div class="board-tools" role="toolbar" aria-label="Strumenti lavagna">${[['move','Sposta'],['arrow','Freccia'],['pen','Penna']].map(([k,v])=>`<button class="btn light" data-board-tool="${k}" aria-pressed="${boardTool===k}">${v}</button>`).join('')}<label>Colore <select id="board-color"><option value="#e5f52a">Giallo</option><option value="#ffffff">Bianco</option><option value="#ff916b">Arancione</option></select></label><button class="btn light" id="board-undo">Annulla</button><button class="btn light" id="board-clear">Pulisci disegni</button><button class="btn light" id="board-reset">Ricomincia</button><button class="btn light" id="board-download">Scarica immagine</button></div><div class="board-stage"><canvas id="tactical-canvas" width="600" height="1100" aria-label="Campo da padel interattivo. Usa Sposta e trascina i quattro giocatori o la pallina."></canvas></div><div class="board-access"><label>Elemento <select id="board-player"><option value="0">Giocatore 1</option><option value="1">Giocatore 2</option><option value="2">Giocatore 3</option><option value="3">Giocatore 4</option><option value="4">Pallina</option></select></label><div role="group" aria-label="Sposta l’elemento selezionato">${[['left','←'],['up','↑'],['down','↓'],['right','→']].map(([k,v])=>`<button class="btn light" data-board-direction="${k}" aria-label="Sposta ${ {left:'a sinistra',up:'in alto',down:'in basso',right:'a destra'}[k]}">${v}</button>`).join('')}</div></div><p class="board-help">Trascina con il dito o il mouse. Le modifiche restano durante la navigazione, fino all’aggiornamento della pagina. Scarica l’immagine per conservarla.</p><p id="board-status" class="board-help" role="status"></p></section>`}
function mountBoard(){
 const canvas=$('#tactical-canvas');if(!canvas)return;const c=canvas.getContext('2d');let gesture=null;
 const snapshot=()=>JSON.stringify(boardState);const remember=s=>{boardUndo.push(s);if(boardUndo.length>60)boardUndo.shift()};
 const say=s=>{$('#board-status').textContent=s};
 const point=e=>{const r=canvas.getBoundingClientRect();return {x:Math.max(30,Math.min(470,(e.clientX-r.left)*600/r.width-50)),y:Math.max(30,Math.min(970,(e.clientY-r.top)*1100/r.height-50))}};
 function draw(){c.clearRect(0,0,600,1100);c.fillStyle='#edf4f9';c.fillRect(0,0,600,1100);c.save();c.translate(50,50);c.fillStyle='#0867a6';c.fillRect(0,0,500,1000);c.strokeStyle='#fff';c.lineWidth=4;c.strokeRect(0,0,500,1000);c.beginPath();c.moveTo(0,150);c.lineTo(500,150);c.moveTo(0,850);c.lineTo(500,850);c.moveTo(250,150);c.lineTo(250,850);c.stroke();c.strokeStyle='#bce8ff';c.lineWidth=9;c.strokeRect(-8,-8,516,1016);c.strokeStyle='#102f49';c.lineWidth=9;c.beginPath();c.moveTo(-12,500);c.lineTo(512,500);c.stroke();c.setLineDash([8,7]);c.strokeStyle='#fff';c.lineWidth=3;c.stroke();c.setLineDash([]);
 for(const l of boardState.lines){c.strokeStyle=l.color;c.fillStyle=l.color;c.lineWidth=6;c.lineCap='round';c.lineJoin='round';c.beginPath();l.points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke();if(l.type==='arrow'&&l.points.length>1){const a=l.points[0],b=l.points.at(-1),ang=Math.atan2(b.y-a.y,b.x-a.x);c.beginPath();c.moveTo(b.x,b.y);c.lineTo(b.x-24*Math.cos(ang-.5),b.y-24*Math.sin(ang-.5));c.lineTo(b.x-24*Math.cos(ang+.5),b.y-24*Math.sin(ang+.5));c.closePath();c.fill()}}
 boardState.players.forEach((p,i)=>{c.beginPath();c.arc(p.x,p.y,i===4?14:25,0,Math.PI*2);c.fillStyle=i===4?'#e5f52a':i<2?'#fff':'#ff916b';c.fill();c.lineWidth=3;c.strokeStyle='#122f49';c.stroke();if(i<4){c.fillStyle='#122f49';c.font='bold 24px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(i+1,p.x,p.y)}});c.restore();$('#board-undo').disabled=!boardUndo.length;}
 canvas.addEventListener('pointerdown',e=>{if(gesture||e.button!==0)return;const p=point(e),before=snapshot();let index=-1;if(boardTool==='move'){index=boardState.players.findIndex(q=>Math.hypot(p.x-q.x,p.y-q.y)<40);if(index<0)return}else boardState.lines.push({type:boardTool,color:boardColor,points:[p,p]});gesture={id:e.pointerId,index,before};canvas.setPointerCapture(e.pointerId);e.preventDefault();draw()});
 canvas.addEventListener('pointermove',e=>{if(!gesture||gesture.id!==e.pointerId)return;const p=point(e);if(gesture.index>=0)boardState.players[gesture.index]=p;else {const l=boardState.lines.at(-1);if(l.type==='arrow')l.points[1]=p;else if(l.points.length<3000)l.points.push(p)}draw()});
 const finish=e=>{if(!gesture||gesture.id!==e.pointerId)return;const g=gesture;gesture=null;if(e.type==='pointercancel')boardState=JSON.parse(g.before);else if(snapshot()!==g.before)remember(g.before);draw()};canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);canvas.addEventListener('lostpointercapture',finish);
 document.querySelectorAll('[data-board-tool]').forEach(b=>b.onclick=()=>{boardTool=b.dataset.boardTool;document.querySelectorAll('[data-board-tool]').forEach(x=>x.setAttribute('aria-pressed',x===b));canvas.style.cursor=boardTool==='move'?'grab':'crosshair'});
 $('#board-color').value=boardColor;$('#board-color').onchange=e=>boardColor=e.target.value;
 $('#board-undo').onclick=()=>{if(boardUndo.length){boardState=JSON.parse(boardUndo.pop());draw();say('Ultima modifica annullata.')}};
 $('#board-clear').onclick=()=>{if(boardState.lines.length){remember(snapshot());boardState.lines=[];draw();say('Disegni rimossi. Puoi annullare.')}};
 $('#board-reset').onclick=()=>{remember(snapshot());boardState=boardInitial();draw();say('Campo ripristinato. Puoi annullare.')};
 document.querySelectorAll('[data-board-direction]').forEach(b=>b.onclick=()=>{remember(snapshot());const p=boardState.players[Number($('#board-player').value)],d=b.dataset.boardDirection;p.x=Math.max(30,Math.min(470,p.x+(d==='left'?-20:d==='right'?20:0)));p.y=Math.max(30,Math.min(970,p.y+(d==='up'?-20:d==='down'?20:0)));draw()});
 $('#board-download').onclick=()=>{draw();const a=document.createElement('a');a.download='lavagna-padel-'+today()+'.png';a.href=canvas.toDataURL('image/png');a.click();say('Immagine pronta per il download.')};draw();
}
