// Schede personali: valutazioni generali e resoconti delle lezioni restano distinti.
let activeStudent = null;
let activeTab = 'allenamenti';
let entryCounter = Date.now();
function nextId(){entryCounter=Math.max(entryCounter+1,Date.now());return entryCounter}
const generalHistory=[];
const journals=[];
const gradeLabels = ['Non valutato','1 · In acquisizione','2 · Di base','3 · Consolidato','4 · Avanzato','5 · Molto consolidato'];
const gradeText = n => n ? `${n}/5` : 'Non valutato';
const byDate = (a,b) => b.date.localeCompare(a.date) || b.id-a.id;
const historyFor = id => generalHistory.filter(h=>h.student===id).sort(byDate);
const currentRating = id => historyFor(id)[0]||{overall:0,date:'',scores:[0,0,0,0,0],goal:people.find(p=>p.id===id)?.goal||'Da definire',note:'Nessuna valutazione registrata.'};
const journalsFor = id => journals.filter(j=>j.student===id&&(!activeCourse||j.course_id===activeCourse)).sort((a,b)=>b.date.localeCompare(a.date)||b.time.localeCompare(a.time)||b.id-a.id);
const shortDate = d => !d?'Non ancora valutato':new Date(d+'T12:00:00').toLocaleDateString('it-IT',{day:'numeric',month:'short',year:'numeric'});
function gradeOptions(value,required=false){return gradeLabels.map((label,i)=>`<option value="${i||''}" ${Number(value)===i?'selected':''} ${required&&i===0?'disabled':''}>${label}</option>`).join('')}

function navigate(value){
 const parts=String(value).split('/');let [section,id]=parts;
 if(section==='allenamenti'||section==='progressi')section='allievi';
 route=['oggi','agenda','allievi','corsi','lavagna','backup','condivisione'].includes(section)?section:'oggi';
 activeCourse=route==='corsi'&&courses.some(c=>c.id===Number(id))?Number(id):null;
 activeStudent=route==='allievi'?(people.some(p=>p.id===Number(id)&&studentAccess(p.id))?Number(id):null):activeCourse&&parts[2]==='allievi'&&courseStudents.some(s=>s.course_id===activeCourse&&s.student===Number(parts[3]))?Number(parts[3]):null;
 activeTab='allenamenti';query='';render();
 history.replaceState(null,'','#'+route+(activeCourse?'/'+activeCourse:'')+(activeStudent?(activeCourse?'/allievi/':'/')+activeStudent:''));
}

function render(){

  const routes=['oggi','agenda','allievi','corsi','lavagna','condivisione','backup'];
  $('#nav').innerHTML=routes.map(r=>`<a href="#${r}" class="${route===r?'active':''}" ${route===r?'aria-current="page"':''}>${svg(r)}${names[r]}</a>`).join('');
  $('#crumb').textContent=route==='allievi'?(activeStudent?people.find(p=>p.id===activeStudent).name:'Allievi'):names[route];
  $('.profile').innerHTML='<span class="avatar">MC</span><div><strong>Il mio diario</strong><small>Maestro di padel</small></div>';
  $('#app').innerHTML=route==='lavagna'?boardPage():route==='condivisione'?sharingPage():route==='backup'?backupPage():route==='oggi'?home():route==='agenda'?agenda():route==='corsi'&&!activeStudent?(activeCourse?courseView(activeCourse):courseList()):activeStudent?studentProfile(activeStudent):students();
  if(route==='lavagna')mountBoard();
}
function home(){
 const current=today(),now=new Date(),clock=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0');
 const mine=lessons.filter(l=>!l.cancelled&&l.date===current).sort((a,b)=>a.time.localeCompare(b.time));
 const upcoming=lessons.filter(l=>!l.cancelled&&(l.date>current||(l.date===current&&l.time>=clock))).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time))[0];
 const recent=[...journals].sort(byDate).slice(0,3),pending=lessons.filter(l=>!l.cancelled&&(l.date<current||(l.date===current&&l.time<clock))&&missingJournals(l).length).sort((a,b)=>b.date.localeCompare(a.date)||b.time.localeCompare(a.time));
 const focus=upcoming?`<div class="eyebrow">Prossima lezione</div><h2>${esc(who(upcoming))}</h2><p>${esc(upcoming.focus)}</p><div class="focus-meta"><div><strong>${upcoming.time}</strong>${shortDate(upcoming.date)}</div><div><strong>${upcoming.duration} min</strong>${esc(upcoming.club)}</div></div><button class="btn lime" data-action="lesson" data-id="${upcoming.id}">Apri lezione</button>`:`<div class="eyebrow">La tua agenda</div><h2>Spazio alla prossima lezione.</h2><p>Organizza il prossimo appuntamento e ritrova qui l’obiettivo su cui lavorare.</p><button class="btn lime" data-action="new-lesson">＋ Nuova lezione</button>`;
 return title(dateLabel(current),'Il diario di oggi.','Le lezioni in programma e gli appunti da completare.','<button class="btn" data-action="new-lesson">＋ Nuova lezione</button>')+`<div class="daily-layout"><section class="panel"><div class="panel-head"><h2>In campo oggi</h2><a class="text-link" href="#agenda">Agenda</a></div>${mine.map(lessonRow).join('')||'<div class="empty"><h3>Oggi nessuna lezione in agenda.</h3><p>Puoi dedicarti alle osservazioni degli ultimi allenamenti.</p></div>'}</section><aside class="daily-side"><section class="panel focus-panel">${focus}</section><section class="panel"><div class="panel-head"><h2>Da annotare</h2><span class="tag orange">${pending.length}</span></div>${pending.slice(0,3).map(l=>`<div class="task-row"><strong>${esc(who(l))}</strong><small>${shortDate(l.date)} · ${l.time} · ${esc(l.focus)}</small><button class="btn light" data-action="lesson" data-id="${l.id}">${missingJournals(l).length} schede da annotare</button></div>`).join('')||'<p>Non ci sono lezioni passate da annotare.</p>'}</section></aside></div><div class="overview-strip"><div><strong>${mine.length}</strong><span>lezioni oggi</span></div><div><strong>${people.length}</strong><span>allievi nel diario</span></div><div><strong>${journals.length}</strong><span>allenamenti annotati</span></div></div><div class="section-heading"><div><h2>Ultime pagine del diario</h2><p>Esercizi, osservazioni e andamento delle lezioni.</p></div><a class="text-link" href="#allievi">Allievi</a></div>${recent.map(journalSummary).join('')||'<section class="panel empty"><h3>Ogni percorso comincia da una lezione.</h3><p>Apri la scheda di un allievo per registrare il primo allenamento.</p></section>'}`;
}

function students(){
  const list=people.filter(p=>studentAccess(p.id)&&p.name.toLowerCase().includes(query.toLowerCase()));
  return title('Il lavoro sul campo, nel tempo','Allievi e allenamenti','Obiettivi, allenamenti e osservazioni per ogni percorso.','<button class="btn" data-action="student-new">＋ Nuovo allievo</button>')+
  `<div class="toolbar"><input id="search-people" aria-label="Cerca un allievo" placeholder="Cerca un allievo…" value="${esc(query)}"></div><div class="grid">${list.map(p=>{const rating=currentRating(p.id),entries=journalsFor(p.id);return `<article class="panel card"><div class="person"><span class="avatar">${esc(p.initials)}</span><div><h3>${esc(p.name)}</h3><small>${esc(p.level)} · ${esc(p.side)}</small></div></div><div class="student-numbers"><div><small>Voto generale</small><strong>${gradeText(rating.overall)}</strong></div><div><small>Allenamenti</small><strong>${entries.length}</strong></div></div>${permissionBadge(p)}<div class="goal-label">Obiettivo attuale</div><p class="card-goal">${esc(rating.goal)}</p><small>${entries.length?'Ultima lezione · '+shortDate(entries[0].date):'Nessun allenamento annotato'}</small><a class="btn light" href="#allievi/${p.id}">Apri scheda ↗</a></article>`}).join('')||'<div class="panel empty"><h2>Comincia dalla prima scheda.</h2><p>Aggiungi un allievo per iniziare il suo diario.</p></div>'}</div>`;
}
function studentProfile(id){
  const p=people.find(p=>p.id===id),rating=activeCourse?{overall:0,date:'',goal:courses.find(c=>c.id===activeCourse)?.description||'Allenamenti del corso'}:currentRating(id),entries=journalsFor(id);
  return `${activeCourse?`<a class="text-link back-link" href="#corsi/${activeCourse}">← Cartella del corso</a>`:'<a class="text-link back-link" href="#allievi">← Tutti gli allievi</a>'}`+
  title(activeCourse?courses.find(c=>c.id===activeCourse)?.name||'Diario del corso':'Scheda personale',p.name,`${esc(p.level)} · ${esc(p.side)} · ${entries.length} allenamenti ${'registrati'}`,editScope(id)?`<button class="btn" data-action="journal-new" data-id="${id}">＋ Registra allenamento</button><button class="btn light" data-action="student-edit" data-id="${id}">Modifica allievo</button><button class="btn light danger" data-action="student-delete" data-id="${id}">Elimina allievo</button>${!activeCourse?`<button class="btn light" data-action="file-share" data-kind="student" data-id="${id}">Esporta diario</button>`:''}`:'')+
  `<section class="student-overview"><div class="student-goal"><div class="eyebrow">Su cosa stiamo lavorando</div><h2>${esc(rating.goal)}</h2><p>${entries.length?'Ultimo allenamento · '+shortDate(entries[0].date):'Il percorso prende forma, una lezione alla volta.'}</p></div>${!activeCourse?`<div class="rating-summary"><div class="eyebrow">Valutazione attuale</div><div class="overall-number">${rating.overall||'—'}<span>/ 5</span></div><small>${rating.date?shortDate(rating.date):'Non ancora valutato'}</small></div>`:''}${!activeCourse&&studentAccess(id,true)?`<button class="btn light" data-action="general-new" data-id="${id}">Aggiorna valutazione</button>`:''}</section>
  <div class="profile-tabs" role="tablist" aria-label="Scheda allievo"><button role="tab" aria-selected="${activeTab==='allenamenti'}" data-action="profile-tab" data-tab="allenamenti" class="${activeTab==='allenamenti'?'selected':''}">Allenamenti <span>${entries.length}</span></button>${!activeCourse?`<button role="tab" aria-selected="${activeTab==='generale'}" data-action="profile-tab" data-tab="generale" class="${activeTab==='generale'?'selected':''}">Valutazione generale</button>`:''}<button role="tab" aria-selected="${activeTab==='progressi'}" data-action="profile-tab" data-tab="progressi" class="${activeTab==='progressi'?'selected':''}">Progressi</button>${!activeCourse?`<button role="tab" aria-selected="${activeTab==='storico'}" data-action="profile-tab" data-tab="storico" class="${activeTab==='storico'?'selected':''}">Storico voti</button>`:''}</div>
  <section role="tabpanel">${activeTab==='allenamenti'?`<div class="panel-head"><h2>Diario degli allenamenti</h2><span class="muted">Dal più recente</span></div>${entries.length?entries.map(journalSummary).join(''):`<div class="panel empty"><h2>Il diario comincia dalla prossima lezione.</h2><p>${'Annota gli esercizi svolti, come sono andati e il voto della lezione.'}</p>${editScope(id)?`<button class="btn" data-action="journal-new" data-id="${id}">Registra il primo allenamento</button>`:''}</div>`}`:activeTab==='generale'?generalView(rating):activeTab==='progressi'?progressView(id):historyView(id)}</section>`;
}
function journalSummary(j){
  const student=people.find(p=>p.id===j.student);
  return `<article class="journal-card"><div class="journal-date"><strong>${new Date(j.date+'T12:00:00').getDate()}</strong><span>${new Date(j.date+'T12:00:00').toLocaleDateString('it-IT',{month:'short',year:'numeric'})}</span></div><div class="journal-info"><small>${activeStudent?'':esc(student?.name||'Allievo')+' · '}${j.time} · ${esc(j.club)}</small><h3>${esc(j.title)}</h3><p>${j.exercises.length} esercizi · ${esc(j.exercises.map(e=>e.name).join(' · '))}</p>${permissionBadge(j)}</div><div class="journal-end"><span class="lesson-grade">${gradeText(j.grade)}</span><small>Voto lezione</small><button class="btn light" data-action="journal-open" data-id="${j.id}">Apri scheda ↗</button></div></article>`;
}
function generalView(rating){return `<section class="panel"><div class="panel-head"><h2>Valutazione attuale</h2><span class="tag">${shortDate(rating.date)}</span></div>${skillNames.map((s,i)=>`<div class="progress-row"><div class="progress-title"><span>${s}</span><strong>${gradeText(rating.scores[i])}</strong></div><div class="bar"><i style="width:${rating.scores[i]*20}%"></i></div></div>`).join('')}<div class="written-note"><h3>Osservazioni sulla valutazione</h3><p>${esc(rating.note)}</p></div><details class="scale-help"><summary>Come leggere le valutazioni</summary><p>1 · In acquisizione / 2 · Di base / 3 · Consolidato / 4 · Avanzato / 5 · Molto consolidato.</p><p>La valutazione generale descrive il percorso e resta distinta dal voto della singola lezione. Scala didattica interna.</p></details></section>`}
function historyView(id){const list=historyFor(id);return `<section class="panel"><div class="panel-head"><h2>Come cambia il voto generale</h2><span class="tag">${list.length} valutazioni</span></div><p>Ogni aggiornamento conserva la valutazione precedente. I voti delle singole lezioni restano nel diario.</p><div class="rating-timeline">${list.map((r,i)=>{const previous=list[i+1];return `<article class="history-entry"><div class="history-mark">${r.overall}</div><div><h3>${shortDate(r.date)} <span class="tag">${i===0?'Attuale':'Precedente'}</span></h3><p><strong>${previous?previous.overall+' → '+r.overall+'/5':'Prima valutazione · '+r.overall+'/5'}</strong></p><p>${esc(r.note)}</p><small>Obiettivo: ${esc(r.goal)}</small><details><summary>Valutazioni per area</summary>${skillNames.map((s,n)=>`<div class="rating"><span>${s}</span><strong>${gradeText(r.scores[n])}</strong></div>`).join('')}</details></div></article>`}).join('')}</div></section>`}
function exerciseFields(e={name:'',execution:''}){return `<fieldset class="exercise-fields"><legend>Esercizio svolto</legend><label class="field">Esercizio<input name="exerciseName" value="${esc(e.name)}" maxlength="180" required placeholder="Scrivi cosa avete fatto"></label><label class="field">Come è stato eseguito<textarea name="execution" maxlength="2500" required placeholder="Cosa è riuscito, difficoltà e correzioni…">${esc(e.execution)}</textarea></label><button type="button" class="btn ghost remove-row" data-action="exercise-remove">Rimuovi esercizio</button></fieldset>`}
function editJournal(studentId,entryId=null,lessonId=null){

  const p=people.find(p=>p.id===studentId);let entry=entryId?journals.find(j=>j.id===entryId&&j.student===studentId):null;
  const lesson=lessonId?lessons.find(l=>l.id===lessonId):null;
  const courseId=entry?.course_id||lesson?.course_id||activeCourse||null;if(!contextAccess(studentId,courseId,true))return;
  const j=entry||{date:lesson?.date||selectedDate,time:lesson?.time||'17:00',club:lesson?.club||'',title:lesson?.focus||'',grade:0,notes:'',privateNote:'',exercises:[{name:'',execution:''}]};
  modal(entry?'Modifica allenamento':'Registra allenamento',`<p>${esc(p.name)}</p><form id="journal-form" data-student="${studentId}" data-entry="${entry?.id||''}" data-lesson="${entry?.lessonId||lessonId||''}" data-course="${courseId||''}"><div class="form-grid"><label class="field">Data allenamento<input name="date" type="date" value="${j.date}" required></label><label class="field">Orario<input name="time" type="time" value="${j.time}" required></label><label class="field full">Titolo allenamento<input name="title" value="${esc(j.title)}" placeholder="Es. Difesa e controllo del pallonetto" maxlength="160" required></label><label class="field full">Circolo<input name="club" value="${esc(j.club)}" maxlength="100" required></label></div><div id="exercise-rows">${j.exercises.map(exerciseFields).join('')}</div><button type="button" class="btn light" data-action="exercise-add">＋ Altro esercizio</button><div class="form-grid journal-final"><label class="field full">Voto della lezione<select name="grade" aria-label="Voto della lezione">${gradeOptions(j.grade)}</select></label><label class="field full">Commento sulla lezione<textarea name="notes" maxlength="4000" placeholder="Andamento generale e aspetti da riprendere…">${esc(j.notes)}</textarea></label>${owns(p)?`<label class="field full">Nota privata del coach<textarea name="privateNote" maxlength="4000" placeholder="Esclusa dai file di condivisione">${esc(j.privateNote||'')}</textarea></label>`:''}</div><p class="form-help">Puoi esportare questa scheda dopo averla salvata. La nota privata è esclusa dal file di condivisione. Il voto generale non cambia.</p><div class="form-actions"><button type="button" class="btn light" data-action="close">Annulla</button><button class="btn" type="submit">Salva allenamento</button></div></form>`);
}
function openJournal(id){
  const j=journals.find(j=>j.id===id);if(!j)return;
  const p=people.find(p=>p.id===j.student);
  modal(esc(j.title),`<p>${esc(p.name)} · ${shortDate(j.date)} · ${j.time}</p><div class="chips"><span class="tag">${esc(j.club)}</span><span class="tag blue">Voto lezione: ${gradeText(j.grade)}</span>${permissionBadge(j)}</div>${j.exercises.map((e,i)=>`<section class="exercise-report"><small>ESERCIZIO ${i+1}</small><h3>${esc(e.name)}</h3><p>${esc(e.execution)}</p></section>`).join('')}<section class="written-note"><h3>Commento sulla lezione</h3><p>${esc(j.notes)||'Nessun commento aggiunto.'}</p></section>${j.privateNote?`<section class="notice private-note"><h3>Nota privata · solo coach</h3><p>${esc(j.privateNote)}</p></section>`:''}<div class="form-actions">${canWriteJournal(j)?`<button class="btn light" data-action="student" data-id="${j.student}">Scheda allievo</button><button class="btn" data-action="journal-edit" data-id="${j.id}">Modifica allenamento</button><button class="btn light" data-action="file-share" data-kind="journal" data-id="${j.id}">Esporta allenamento</button>`:'<button class="btn light" data-action="close">Chiudi</button>'}</div>`);
}
function editGeneral(id){
  if(activeCourse||!studentAccess(id,true))return;const p=people.find(p=>p.id===id),r=currentRating(id);
  modal('Aggiorna voto generale',`<p>${esc(p.name)}</p><form id="general-form" data-id="${id}"><div class="form-grid"><label class="field">Data valutazione<input name="date" type="date" value="${today()}" required></label><label class="field">Voto generale<select name="overall" aria-label="Voto generale" required>${gradeOptions(r.overall,true)}</select></label></div><div class="notice">Crea una nuova voce nello storico. Il voto generale è assegnato dal coach e non è la media automatica dei voti delle lezioni.</div>${skillNames.map((s,i)=>`<div class="rating"><label for="area-${i}">${s}</label><select id="area-${i}" name="s${i}">${gradeOptions(r.scores[i])}</select></div>`).join('')}<label class="field journal-final">Obiettivo attuale<input name="goal" value="${esc(r.goal)}" maxlength="160" required></label><label class="field journal-final">Motivo e osservazioni<textarea name="note" maxlength="4000" required placeholder="Descrivi cosa è cambiato rispetto alla valutazione precedente…"></textarea></label><p class="form-help">La nuova valutazione resta nel tuo diario e può essere inclusa nell’esportazione del diario dell’allievo.</p><div class="form-actions"><button type="button" class="btn light" data-action="close">Annulla</button><button class="btn" type="submit">Salva nello storico</button></div></form>`);
}
