/* One IndexedDB transaction per save; failed saves keep the previous diary. */
let localReady=false,busy=false,localStore=null,localState=null;
const diaryChannel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('campo-diary'):null;
function snapshot(){return CampoFiles.cleanData({students:people,courses,course_students:courseStudents,lessons,training_sessions:journals,general_ratings:generalHistory})}
function hydrate(data){const d=CampoFiles.cleanData(data);people.splice(0,people.length,...d.students.map(p=>({...p,initials:p.name.split(/\s+/).map(s=>s[0]).slice(0,2).join('').toUpperCase()})));courses.splice(0,courses.length,...d.courses);courseStudents.splice(0,courseStudents.length,...d.course_students);lessons=d.lessons.map(l=>({...l,title:l.focus,players:l.participants.map(p=>p.student),present:l.participants.every(p=>p.present)}));journals.splice(0,journals.length,...d.training_sessions);generalHistory.splice(0,generalHistory.length,...d.general_ratings);entryCounter=Math.max(Date.now(),...CampoFiles.tables.filter(t=>t!=='course_students').map(t=>d[t].reduce((n,r)=>Math.max(n,r.id),0)))}
function openStore(){return new Promise((resolve,reject)=>{const request=indexedDB.open('campo-diario-offline',1);request.onupgradeneeded=()=>request.result.createObjectStore('diary');request.onsuccess=()=>{const db=request.result;db.onversionchange=()=>{db.close();localReady=false;toast('Il diario è stato aggiornato in un’altra finestra. Riapri l’app.')};resolve(db)};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('Chiudi le altre finestre del diario e riprova.'))})}
function readStore(){return new Promise((resolve,reject)=>{const tx=localStore.transaction('diary','readonly'),req=tx.objectStore('diary').get('main');tx.oncomplete=()=>resolve(req.result);tx.onabort=()=>reject(tx.error)})}
function commitStore(data,expectedRevision){const clean=CampoFiles.cleanData(data);return new Promise((resolve,reject)=>{const tx=localStore.transaction('diary','readwrite'),store=tx.objectStore('diary'),req=store.get('main');let next,reason;req.onsuccess=()=>{const old=req.result;if((old?.revision??null)!==expectedRevision){reason=Error('Il diario è cambiato in un’altra finestra. Aggiorna la pagina prima di salvare.');tx.abort();return}next={origin:old?.origin||crypto.randomUUID(),revision:(old?.revision||0)+1,data:clean};store.put(next,'main')};tx.oncomplete=()=>resolve(next);tx.onabort=()=>reject(reason||tx.error||Error('Salvataggio locale non riuscito.'));tx.onerror=()=>{}})}
function saveFailure(error){return error?.name==='QuotaExceededError'?'Spazio sul dispositivo esaurito. Il salvataggio non è riuscito: esporta un backup e libera spazio.':error?.message||'Salvataggio locale non riuscito. I dati precedenti sono conservati.'}
async function mutate(task,done){if(busy||!localReady)return;busy=true;const before=snapshot(),buttons=[...document.querySelectorAll('#modal button,#app button')];buttons.forEach(b=>b.disabled=true);let saved=false;try{await task();localState=await commitStore(snapshot(),localState.revision);saved=true;hydrate(localState.data);diaryChannel?.postMessage(localState.revision);done()}catch(error){hydrate(saved?localState.data:before);if(saved){toast("Dati salvati. Ricarica la pagina per visualizzarli.");return}toast(saveFailure(error));let note=$('#modal .save-error');if($('#modal').open&&!note){note=document.createElement('p');note.className='save-error';note.setAttribute('role','alert');$('#modal').append(note)}if(note)note.textContent=saveFailure(error)}finally{busy=false;buttons.forEach(b=>b.disabled=false)}}
function studentForm(id=null){
 const p=id?people.find(p=>p.id===id):null;if(id&&!p)return;
 const choices=(values,current)=>[...new Set([...values,...(current?[current]:[])])].map(v=>`<option ${v===current?'selected':''}>${esc(v)}</option>`).join('');
 modal(p?'Modifica allievo':'Nuovo allievo',`<form id="student-form" data-id="${p?.id||''}"><label class="field">Nome e cognome<input name="name" maxlength="120" value="${esc(p?.name||'')}" required></label><div class="form-grid"><label class="field">Livello<select name="level">${choices(['Base','Intermedio','Avanzato'],p?.level)}</select></label><label class="field">Lato<select name="side">${choices(['Destra','Sinistra','Entrambi'],p?.side)}</select></label></div><label class="field">${p&&historyFor(id).length?'Obiettivo iniziale':'Obiettivo'}<input name="goal" maxlength="160" value="${esc(p?.goal||'')}" placeholder="Da definire insieme"></label>${p&&historyFor(id).length?'<p class="form-help">Lo storico dei voti resta conservato. Per cambiare l’obiettivo attuale usa “Aggiorna valutazione” nella scheda allievo.</p>':''}<div class="form-actions"><button type="button" class="btn light" data-action="close">Annulla</button><button class="btn">${p?'Salva modifiche':'Crea scheda'}</button></div></form>`);
}
function deleteLessonData(id){lessons=lessons.filter(l=>l.id!==id);journals.forEach(j=>{if(j.lessonId===id)j.lessonId=null})}
function deleteStudentData(id){
 const removed=new Set(lessons.filter(l=>l.players.length===1&&l.players[0]===id).map(l=>l.id));
 lessons=lessons.filter(l=>!removed.has(l.id));lessons.forEach(l=>{l.participants=l.participants.filter(p=>p.student!==id)});
 for(const [array,keep] of [[people,p=>p.id!==id],[journals,j=>j.student!==id],[generalHistory,r=>r.student!==id],[courseStudents,m=>m.student!==id]]){const remaining=array.filter(keep);array.splice(0,array.length,...remaining)}
 journals.forEach(j=>{if(removed.has(j.lessonId))j.lessonId=null});
}
function confirmDelete(kind,id){
 const item=(kind==='lesson'?lessons:people).find(x=>x.id===id);if(!item)return;
 const details=kind==='lesson'?`<p>Eliminare la lezione del <strong>${esc(dateLabel(item.date))} alle ${item.time}</strong> con ${esc(who(item))}?</p><p>La lezione, le presenze e la sua nota privata saranno eliminate. I ${journals.filter(j=>j.lessonId===id).length} allenamenti collegati resteranno nel diario, comprese osservazioni, voti e note private, come schede indipendenti.</p>`:`<p>Eliminare la scheda di <strong>${esc(item.name)}</strong>?</p><p>Verranno eliminati ${journals.filter(j=>j.student===id).length} allenamenti, ${generalHistory.filter(r=>r.student===id).length} valutazioni, le iscrizioni ai corsi e ${lessons.filter(l=>l.players.length===1&&l.players[0]===id).length} lezioni individuali di questo allievo, comprese le relative note private.</p><p>L’allievo sarà rimosso dalle ${lessons.filter(l=>l.players.length>1&&l.players.includes(id)).length} lezioni di gruppo a cui partecipa. Le lezioni e i diari degli altri allievi saranno conservati, così come le cartelle dei corsi.</p>`;
 modal(kind==='lesson'?'Elimina lezione':'Elimina allievo',details+`<p>Per recuperare i dati dopo l’eliminazione serve un backup precedente.</p><button class="btn light" data-action="backup-download">Scarica prima un backup</button><form id="delete-confirm"><label class="share-choice"><input type="checkbox" required> Confermo l’eliminazione descritta</label><div class="form-actions"><button type="button" class="btn light" data-action="close">Annulla</button><button class="btn danger">${kind==='lesson'?'Elimina lezione':'Elimina allievo'}</button></div></form>`);
 $('#delete-confirm').addEventListener('submit',async e=>{e.preventDefault();if(!localReady||busy)return;const cid=activeCourse;await mutate(()=>{if(kind==='lesson')deleteLessonData(id);else deleteStudentData(id)},()=>{close();navigate(kind==='lesson'?(cid?'corsi/'+cid:'agenda'):'allievi');toast(kind==='lesson'?'Lezione eliminata. Allenamenti conservati.':'Scheda allievo eliminata.')})});
}
document.addEventListener('click',async e=>{
 const link=e.target.closest('a[href^="#"]');if(link){e.preventDefault();if(localReady&&!busy){close();navigate(link.getAttribute('href').slice(1))}return}const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,id=Number(el.dataset.id);if(a==='refresh'){location.reload();return}if(!localReady||busy)return;
 if(a==='close')close();else if(a==='new-lesson')newLesson();else if(a==='student-new')studentForm();else if(a==='student-edit')studentForm(id);else if(a==='lesson-edit')newLesson(id);else if(a==='student-delete')confirmDelete('student',id);else if(a==='lesson-delete')confirmDelete('lesson',id);else if(a==='date'){selectedDate=el.dataset.date;render()}else if(a==='lesson')openLesson(id);else if(a==='student'){close();navigate(activeCourse?'corsi/'+activeCourse+'/allievi/'+id:'allievi/'+id)}else if(a==='profile-tab'){activeTab=el.dataset.tab;render()}else if(a==='journal-open')openJournal(id);else if(a==='journal-new')editJournal(id);else if(a==='lesson-journal'){const lid=Number(el.dataset.lesson),existing=journals.find(j=>j.student===id&&j.lessonId===lid);editJournal(id,existing?.id,lid)}else if(a==='journal-edit'){const j=journals.find(j=>j.id===id);if(j)editJournal(j.student,j.id)}else if(a==='general-new')editGeneral(id);else if(a==='exercise-add'){$('#exercise-rows').insertAdjacentHTML('beforeend',exerciseFields());$('#exercise-rows').lastElementChild.querySelector('input').focus()}else if(a==='exercise-remove'){if($('#exercise-rows').children.length===1)return toast('Mantieni almeno un esercizio.');el.closest('fieldset').remove()}else if(a==='presence'){const l=lessons.find(l=>l.id===id),pid=Number(el.dataset.student)||l?.players[0];if(!l||!l.players.includes(pid))return;const inDetail=$('#modal').open;await mutate(()=>{l.participants.find(p=>p.student===pid).present=!participantPresent(l,pid)},()=>{render();if(inDetail)openLesson(id);toast('Presenza aggiornata.')})}else if(a==='save-note'){const l=lessons.find(l=>l.id===id);if(l)await mutate(()=>{l.note=$('#lesson-note').value},()=>{close();toast('Nota privata salvata sul dispositivo.')})}
});
document.addEventListener('submit',async e=>{
 const f=e.target;if(!['student-form','journal-form','general-form','lesson-form'].includes(f.id))return;e.preventDefault();if(!localReady||busy)return;const d=new FormData(f);
 if(f.id==='student-form'){const name=d.get('name').trim();if(!name)return;const existingId=Number(f.dataset.id),old=people.find(p=>p.id===existingId);if(existingId&&!old)return toast('Scheda non più disponibile.');const id=existingId||nextId(),cid=activeCourse,entry={...old,id,name,level:d.get('level'),side:d.get('side'),goal:d.get('goal').trim()};await mutate(()=>{const i=people.findIndex(p=>p.id===id);if(i<0)people.push(entry);else people[i]=entry},()=>{close();navigate(cid?'corsi/'+cid+'/allievi/'+id:'allievi/'+id);toast(old?'Scheda allievo aggiornata.':'Scheda creata.')})}
 else if(f.id==='journal-form'){const student=Number(f.dataset.student),entryId=Number(f.dataset.entry),existing=journals.find(j=>j.id===entryId),rows=[...f.querySelectorAll('.exercise-fields')].map(row=>({name:row.querySelector('[name="exerciseName"]').value.trim(),execution:row.querySelector('[name="execution"]').value.trim()}));if(!rows.length||rows.some(r=>!r.name||!r.execution)||!d.get('title').trim())return toast('Completa titolo, esercizi e osservazioni.');const entry={...existing,id:entryId||nextId(),student,lessonId:Number(f.dataset.lesson)||null,course_id:Number(f.dataset.course)||null,date:d.get('date'),time:d.get('time'),club:d.get('club').trim(),title:d.get('title').trim(),grade:Number(d.get('grade')),notes:d.get('notes').trim(),privateNote:d.get('privateNote').trim(),exercises:rows};await mutate(()=>{const i=journals.findIndex(j=>j.id===entry.id);if(i<0)journals.push(entry);else journals[i]=entry},()=>{close();navigate(entry.course_id?'corsi/'+entry.course_id+'/allievi/'+student:'allievi/'+student);toast('Allenamento salvato sul dispositivo.')})}
 else if(f.id==='general-form'){const student=Number(f.dataset.id),entry={id:nextId(),student,date:d.get('date'),overall:Number(d.get('overall')),scores:skillNames.map((_,i)=>Number(d.get('s'+i))),goal:d.get('goal').trim(),note:d.get('note').trim()};if(!entry.goal||!entry.note||entry.overall<1||entry.overall>5)return toast('Completa voto, obiettivo e osservazioni.');await mutate(()=>generalHistory.push(entry),()=>{close();activeTab='storico';render();toast('Valutazione aggiunta allo storico.')})}
 else if(f.id==='lesson-form'){
  const participants=[...new Set(d.getAll('students').map(Number))],cid=Number(f.dataset.course)||null,existingId=Number(f.dataset.id),old=lessons.find(l=>l.id===existingId);
  if(existingId&&!old)return toast('Lezione non più disponibile.');
  if(participants.length<1||participants.length>4||participants.some(id=>!contextAccess(id,cid))){$('#form-error').textContent='Seleziona da 1 a 4 allievi disponibili in questo spazio.';return}
  const entry={...old,id:existingId||nextId(),course_id:cid,date:d.get('date'),time:d.get('time'),duration:Number(d.get('duration')),club:d.get('club').trim(),focus:d.get('focus').trim(),note:old?.note||'',cancelled:old?.cancelled||false,participants:participants.map(student=>({student,present:old?.participants.find(p=>p.student===student)?.present||false}))};
  if(!entry.club||!entry.focus){$('#form-error').textContent='Completa circolo e obiettivo.';return}
  if(hasConflict(entry.date,entry.time,entry.duration,existingId||null)){$('#form-error').textContent='Hai già una lezione in questo orario.';return}
  await mutate(()=>{const i=lessons.findIndex(l=>l.id===entry.id);if(i<0)lessons.push(entry);else lessons[i]=entry;for(const j of journals.filter(j=>j.lessonId===entry.id)){if(!participants.includes(j.student))j.lessonId=null;else {j.date=entry.date;j.time=entry.time;j.club=entry.club}}},()=>{selectedDate=entry.date;club='Tutti i circoli';close();navigate('agenda');toast(old?'Lezione aggiornata.':'Lezione salvata in agenda.')});
 }
});
document.addEventListener('change',e=>{if(!localReady||busy)return;if(e.target.id==='club'){club=e.target.value;render()}else if(e.target.id==='agenda-date'){selectedDate=e.target.value||today();render()}if(e.target.name==='students'&&e.target.closest('#lesson-form')){const boxes=[...document.querySelectorAll('[name="students"]')],count=boxes.filter(b=>b.checked).length;boxes.forEach(b=>b.disabled=!b.checked&&count>=4);$('#participant-count').textContent=count+' di 4 selezionati';$('#form-error').textContent=''}if(e.target.id==='progress-area'){progressArea=e.target.value;render();$('#progress-area').focus()}});
document.addEventListener('input',e=>{if(e.target.id==='search-people'){const pos=e.target.selectionStart;query=e.target.value;render();$('#search-people').focus();$('#search-people').setSelectionRange(pos,pos)}});
window.addEventListener('hashchange',()=>{if(localReady&&!busy)navigate(location.hash.slice(1)||'oggi')});$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')&&!busy)close()});$('#modal').addEventListener('cancel',e=>{if(busy)e.preventDefault()});
if(diaryChannel)diaryChannel.onmessage=async()=>{if(busy||$('#modal').open){toast('Diario aggiornato in un’altra finestra. Ricarica prima di salvare.');return}try{localState=await readStore();hydrate(localState.data);navigate(location.hash.slice(1)||'oggi')}catch(e){toast(saveFailure(e))}};
async function startDiary(){try{localStore=await openStore();localState=await readStore();if(!localState){try{localState=await commitStore(CampoFiles.empty(),null)}catch(e){localState=await readStore();if(!localState)throw e}}hydrate(localState.data);localReady=true;navigate(location.hash.slice(1)||'oggi')}catch(error){$('#app').innerHTML=title('Diario locale','Non riesco ad aprire il diario',saveFailure(error))+'<section class="panel"><p>Usa il browser normale, consenti l’archiviazione dei dati e riapri l’app. Non cancellare i dati del browser se hai un diario da recuperare.</p><button class="btn" data-action="refresh">Riprova</button></section>'}}
