const courses=[],courseStudents=[];
let activeCourse=null;
const owns=item=>!!item;
function studentAccess(id){return people.some(p=>p.id===id)}
function courseAccess(id){return courses.some(c=>c.id===id)}
function contextAccess(id,cid=null){return studentAccess(id)&&(!cid||courseAccess(cid)&&courseStudents.some(s=>s.course_id===cid&&s.student===id))}
const canWriteJournal=j=>contextAccess(j.student,j.course_id);
function editScope(id){return contextAccess(id,activeCourse)}
function availableLessonStudents(){return people.filter(p=>!activeCourse||courseStudents.some(s=>s.course_id===activeCourse&&s.student===p.id))}
function permissionBadge(item){return item.source?'<span class="tag blue">Copia importata</span>':''}
function courseList(){return title('Le cartelle del diario','Corsi','Allievi, lezioni e schede organizzati per corso.','<button class="btn" data-action="course-new">＋ Nuovo corso</button>')+`<div class="grid">${courses.map(c=>`<article class="panel card"><div class="panel-head"><h2>${esc(c.name)}</h2></div>${permissionBadge(c)}<p>${esc(c.description||'Nessuna descrizione.')}</p><small>${courseStudents.filter(s=>s.course_id===c.id).length} allievi · ${lessons.filter(l=>l.course_id===c.id&&!l.cancelled).length} lezioni</small><a class="btn light" href="#corsi/${c.id}">Apri cartella</a></article>`).join('')||'<section class="panel empty"><h2>Il primo corso comincia qui.</h2><p>Crea una cartella per organizzare il diario.</p></section>'}</div>`}
function courseView(id){
 const c=courses.find(c=>c.id===id);if(!c)return courseList();const students=courseStudents.filter(s=>s.course_id===id).map(s=>people.find(p=>p.id===s.student)).filter(Boolean),list=lessons.filter(l=>l.course_id===id&&!l.cancelled).sort((a,b)=>b.date.localeCompare(a.date)||a.time.localeCompare(b.time));
 return `<a class="text-link back-link" href="#corsi">← Tutti i corsi</a>`+title('Cartella corso',c.name,c.description,`<div class="actions"><button class="btn" data-action="new-lesson">＋ Nuova lezione</button><button class="btn light" data-action="course-edit" data-id="${id}">Modifica cartella</button><button class="btn light" data-action="file-share" data-kind="course" data-id="${id}">Esporta corso</button></div>`)+`${permissionBadge(c)}<p class="form-help">L’esportazione include solo lezioni e schede di questo corso. Le note private restano nel tuo diario.</p><div class="section-heading"><h2>Allievi del corso</h2></div><div class="grid">${students.map(p=>`<article class="panel card"><h3>${esc(p.name)}</h3><p>${journals.filter(j=>j.course_id===id&&j.student===p.id).length} schede nel corso</p><a class="btn light" href="#corsi/${id}/allievi/${p.id}">Apri diario del corso</a></article>`).join('')||'<p>Nessun allievo iscritto. Aggiungili da “Modifica cartella”.</p>'}</div><div class="section-heading"><h2>Lezioni del corso</h2></div><section class="panel">${list.map(l=>`<div class="course-lesson-date">${dateLabel(l.date)}</div>${lessonRow(l)}`).join('')||'<p>Nessuna lezione inserita.</p>'}</section>`;
}
function courseForm(id=null){const c=courses.find(c=>c.id===id);modal(c?'Modifica cartella':'Nuovo corso',`<form id="course-form" data-id="${id||''}"><label class="field">Nome del corso<input name="name" required maxlength="120" value="${esc(c?.name||'')}" placeholder="Es. Intermedi · martedì sera"></label><label class="field">Descrizione<textarea name="description" maxlength="2000">${esc(c?.description||'')}</textarea></label><fieldset class="participant-picker"><legend>Allievi del corso</legend>${people.map(p=>`<label><input type="checkbox" name="members" value="${p.id}" ${courseStudents.some(s=>s.course_id===id&&s.student===p.id)?'checked':''}><span>${esc(p.name)}</span></label>`).join('')||'<p>Aggiungi prima le schede dei tuoi allievi.</p>'}</fieldset><p class="form-help">Gli allievi con lezioni o allenamenti nel corso devono restare iscritti per conservare lo storico.</p><div class="form-actions"><button type="button" class="btn light" data-action="close">Annulla</button><button class="btn">Salva cartella</button></div></form>`)}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||!localReady||busy)return;if(el.dataset.action==='course-new')courseForm();else if(el.dataset.action==='course-edit')courseForm(Number(el.dataset.id))});
document.addEventListener('submit',async e=>{const f=e.target;if(f.id!=='course-form')return;e.preventDefault();if(!localReady||busy)return;const d=new FormData(f),id=Number(f.dataset.id)||nextId(),old=courses.find(c=>c.id===id),members=[...new Set(d.getAll('members').map(Number))],name=d.get('name').trim();if(!name)return;const required=new Set([...lessons.filter(l=>l.course_id===id).flatMap(l=>l.players),...journals.filter(j=>j.course_id===id).map(j=>j.student)]);if([...required].some(s=>!members.includes(s)))return toast('Mantieni iscritti gli allievi con lezioni o allenamenti nel corso.');await mutate(()=>{const entry={...old,id,name,description:d.get('description').trim()},i=courses.findIndex(c=>c.id===id);if(i<0)courses.push(entry);else courses[i]=entry;const keep=courseStudents.filter(m=>m.course_id!==id);courseStudents.splice(0,courseStudents.length,...keep,...members.map(student=>({course_id:id,student})))},()=>{close();navigate('corsi/'+id);toast('Cartella salvata sul dispositivo.')})});
